#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Flow:
    persistence:

      # It is good practice to not specify user name and password of the database
      # connection in this global Settings.yaml file. Rather specify them in the
      # settings of the respective context (Production / Development ...).
      backendOptions:
        host: 'mysqlsdb.co8hm2var4k9.eu-west-1.rds.amazonaws.com'    # adjust to your database host
        dbname: 'depmgbzcc8f'       # adjust to your database name
        user: 'depmgbzcc8f'             # adjust to your database user
        password: 'NsiEJjYCL01g'         # adjust to your database password

  # You might need to uncomment the following lines and specify
  # the location of the PHP binary manually.
  #  core:
  #    phpBinaryPathAndFilename: 'C:/path/to/php.exe'
